# Generated by Django 2.1 on 2018-08-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_aplicacion',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
