# Generated by Django 2.1 on 2018-08-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_examen', models.CharField(choices=[('MM', 'MMPI-II'), ('GD', 'Gordon'), ('MS', 'Moss'), ('TM', 'Terman Meril')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=70)),
                ('respuesta', models.CharField(max_length=10)),
            ],
        ),
    ]
