# Generated by Django 2.1 on 2018-08-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
